# Generated by Django 2.2.28 on 2023-03-22 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128, unique=True)),
                ('main_actor', models.CharField(max_length=128)),
                ('likes', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=2500)),
                ('trailer_link', models.CharField(blank=True, default='', max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.ImageField(blank=True, upload_to='movie_posters')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user_type', models.CharField(choices=[('COUCH_POTATO', 'Couch Potato'), ('CRITIC', 'Critic'), ('CREATOR', 'Creator')], default='COUCH_POTATO', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('review', models.CharField(max_length=2500)),
                ('starnum', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.Movie')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
