# Generated by Django 2.2.28 on 2023-03-11 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('USER', 'User'), ('CREATOR', 'Creator'), ('CRITIC', 'Critic')], default='USER', max_length=32)),
                ('profile_picture', models.ImageField(upload_to='profilepics')),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('main_actor', models.CharField(max_length=128)),
                ('likes', models.IntegerField(default=0)),
                ('poster', models.ImageField(upload_to='posters')),
                ('slug', models.SlugField(unique=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.Category')),
                ('username', models.ManyToManyField(to='RaisinRatings.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.Movie')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.User')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.User'),
        ),
    ]
