# Generated by Django 2.2.28 on 2023-03-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrition',
            new_name='description',
        ),
    ]
