# Generated by Django 2.2.28 on 2023-03-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
