# Generated by Django 2.2.28 on 2023-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='RaisinRatings.Movie'),
        ),
    ]
