# Generated by Django 2.2.28 on 2023-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='starnum',
            field=models.IntegerField(default=0),
        ),
    ]
