# Generated by Django 2.2.28 on 2023-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disliked_movies',
            field=models.ManyToManyField(related_name='dislikes_movies', to='RaisinRatings.Movie'),
        ),
    ]
