# Generated by Django 2.2.28 on 2023-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0002_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
