# Generated by Django 2.2.28 on 2023-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0002_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descrition',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
