# Generated by Django 2.2.28 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0002_auto_20230311_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='username',
        ),
        migrations.AddField(
            model_name='movie',
            name='user_raters',
            field=models.ManyToManyField(related_name='User', to='RaisinRatings.User'),
        ),
    ]
