# Generated by Django 2.2.28 on 2023-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0002_remove_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movie_posters'),
        ),
    ]
