# Generated by Django 2.2.28 on 2023-03-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0003_auto_20230312_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='RaisinRatings.User'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_raters',
            field=models.ManyToManyField(null=True, related_name='User', to='RaisinRatings.User'),
        ),
    ]
