# Generated by Django 2.2.28 on 2023-03-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0003_auto_20230306_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RaisinRatings.Movie'),
            preserve_default=False,
        ),
    ]
