# Generated by Django 2.2.28 on 2023-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0004_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='main_star',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
