# Generated by Django 2.2.28 on 2023-03-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0004_auto_20230312_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_raters',
            field=models.ManyToManyField(related_name='User', to='RaisinRatings.User'),
        ),
    ]
