# Generated by Django 2.2.28 on 2023-03-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaisinRatings', '0005_auto_20230312_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='username',
            new_name='creator',
        ),
    ]
